"""remote inspections

Revision ID: 75a0403f6078
Revises: ed1f3e08fd36
Create Date: 2026-09-26 05:59:29.404616+00:00
"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

revision: str = '75a0403f6078'
down_revision: str | None = 'ed1f3e08fd36'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table('inspection_requests',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('parcel_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Enum('MANUAL', 'RISK', 'RANDOM', 'SIGNAL', name='inspection_reason', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('status', sa.Enum('REQUESTED', 'SUBMITTED', 'ACCEPTED', 'REJECTED', 'EXPIRED', name='inspection_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('requested_by', sa.String(length=128), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('declared_use', sa.Enum('CULTIVATED', 'BUILDING', 'FALLOW', 'CLEANED', 'OTHER', name='declared_use', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('owner_comment', sa.Text(), nullable=True),
    sa.Column('device_location', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('accuracy_m', sa.Float(), nullable=True),
    sa.Column('checks', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('verdict', sa.Enum('PASS', 'SUSPICIOUS', 'FAIL', name='inspection_verdict', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('reviewed_by', sa.String(length=128), nullable=True),
    sa.Column('review_comment', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parcel_id'], ['parcels.id'], name=op.f('fk_inspection_requests_parcel_id_parcels'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inspection_requests')),
    sa.UniqueConstraint('code', name=op.f('uq_inspection_requests_code')),
    sa.UniqueConstraint('token', name=op.f('uq_inspection_requests_token'))
    )
    op.create_index(op.f('ix_inspection_requests_parcel_id'), 'inspection_requests', ['parcel_id'], unique=False)
    op.create_index(op.f('ix_inspection_requests_status'), 'inspection_requests', ['status'], unique=False)
    op.execute("CREATE SEQUENCE IF NOT EXISTS inspection_code_seq START 1")
    # Photos can now belong to an owner report and be taken by the owner.
    op.drop_constraint(op.f("ck_photos_photo_owner_type"), "photos", type_="check")
    op.create_check_constraint("photo_owner_type", "photos", "owner_type IN ('PARCEL', 'SIGNAL', 'INSPECTION')")
    op.drop_constraint(op.f("ck_photos_photo_source"), "photos", type_="check")
    op.create_check_constraint("photo_source", "photos", "source IN ('INSPECTOR', 'CITIZEN', 'OWNER')")
    # Remote inspections are part of the tamper-evident audit log too.
    op.drop_constraint(op.f("ck_status_transitions_entity_type"), "status_transitions", type_="check")
    op.create_check_constraint(
        "entity_type", "status_transitions", "entity_type IN ('PARCEL', 'SIGNAL', 'APPLICATION', 'INSPECTION')"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inspection_requests_status'), table_name='inspection_requests')
    op.drop_index(op.f('ix_inspection_requests_parcel_id'), table_name='inspection_requests')
    op.drop_geospatial_table('inspection_requests')
    op.execute("DROP SEQUENCE IF EXISTS inspection_code_seq")
    op.drop_constraint(op.f("ck_photos_photo_owner_type"), "photos", type_="check")
    op.create_check_constraint("photo_owner_type", "photos", "owner_type IN ('PARCEL', 'SIGNAL')")
    op.drop_constraint(op.f("ck_photos_photo_source"), "photos", type_="check")
    op.create_check_constraint("photo_source", "photos", "source IN ('INSPECTOR', 'CITIZEN')")
    op.drop_constraint(op.f("ck_status_transitions_entity_type"), "status_transitions", type_="check")
    op.create_check_constraint("entity_type", "status_transitions", "entity_type IN ('PARCEL', 'SIGNAL', 'APPLICATION')")
    # ### end Alembic commands ###
