"""initial schema

Revision ID: 43af945b0cc6
Revises: 
Create Date: 2026-09-24 18:22:08.317262+00:00
"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

revision: str = '43af945b0cc6'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    op.execute("CREATE SEQUENCE IF NOT EXISTS signal_tracking_seq START 1")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    op.create_table('geocode_cache',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('address_ru', sa.String(length=512), nullable=True),
    sa.Column('address_kk', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_geocode_cache'))
    )
    op.create_table('knowledge_questions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('lang', sa.Enum('ru', 'kk', name='lang', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('topic', sa.String(length=64), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_questions'))
    )
    op.create_geospatial_table('parcels',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('cadastral_number', sa.String(length=32), nullable=False),
    sa.Column('geometry', Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('centroid', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('area_ha', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('purpose', sa.Enum('IZHS', 'AGRICULTURE', 'COMMERCIAL', 'INDUSTRIAL', 'LPH', name='parcel_purpose', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('owner_type', sa.Enum('PRIVATE', 'LEASE', 'STATE', name='owner_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('address_ru', sa.String(length=255), nullable=False),
    sa.Column('address_kk', sa.String(length=255), nullable=False),
    sa.Column('district', sa.String(length=64), nullable=False),
    sa.Column('lease_until', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('OK', 'UNDER_CHECK', 'VIOLATION', 'IN_REMEDIATION', 'RESOLVED', 'RETURNED_TO_STATE', name='parcel_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('violation_type', sa.Enum('UNUSED', 'SELF_SEIZURE', 'DUMP', 'MISUSE', name='violation_type', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('inspector_id', sa.String(length=64), nullable=True),
    sa.Column('ndvi', sa.Float(), nullable=True),
    sa.Column('ndvi_flagged', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('ndvi_scanned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=32), server_default='seed', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parcels')),
    sa.UniqueConstraint('cadastral_number', name=op.f('uq_parcels_cadastral_number'))
    )
    op.create_geospatial_index('idx_parcels_centroid', 'parcels', ['centroid'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_index('idx_parcels_geometry', 'parcels', ['geometry'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_parcels_deadline_at'), 'parcels', ['deadline_at'], unique=False)
    op.create_index(op.f('ix_parcels_status'), 'parcels', ['status'], unique=False)
    op.create_geospatial_table('photos',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('owner_type', sa.Enum('PARCEL', 'SIGNAL', name='photo_owner_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('thumb_path', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=64), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('source', sa.Enum('INSPECTOR', 'CITIZEN', name='photo_source', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('uploaded_by', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_photos'))
    )
    op.create_index('ix_photos_owner', 'photos', ['owner_type', 'owner_id'], unique=False)
    op.create_table('status_transitions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.Enum('PARCEL', 'SIGNAL', 'APPLICATION', name='entity_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.String(length=32), nullable=True),
    sa.Column('to_status', sa.String(length=32), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_status_transitions'))
    )
    op.create_index('ix_status_transitions_entity', 'status_transitions', ['entity_type', 'entity_id', 'created_at'], unique=False)
    op.create_table('telegram_users',
    sa.Column('chat_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('lang', sa.Enum('ru', 'kk', name='lang', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('signals_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_signal_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('chat_id', name=op.f('pk_telegram_users'))
    )
    op.create_table('tg_processed_updates',
    sa.Column('update_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('update_id', name=op.f('pk_tg_processed_updates'))
    )
    op.create_table('applications',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tracking_number', sa.String(length=32), nullable=False),
    sa.Column('applicant_name', sa.String(length=64), nullable=False),
    sa.Column('type', sa.Enum('PURPOSE_CHANGE', 'LEASE_EXTENSION', 'IZHS_ALLOCATION', name='application_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('status', sa.Enum('UNDER_REVIEW', 'INSPECTION_SCHEDULED', 'APPROVED', 'REJECTED', name='application_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('status_comment_ru', sa.Text(), nullable=True),
    sa.Column('status_comment_kk', sa.Text(), nullable=True),
    sa.Column('inspection_date', sa.Date(), nullable=True),
    sa.Column('parcel_id', sa.UUID(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parcel_id'], ['parcels.id'], name=op.f('fk_applications_parcel_id_parcels'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_applications')),
    sa.UniqueConstraint('tracking_number', name=op.f('uq_applications_tracking_number'))
    )
    op.create_index(op.f('ix_applications_status'), 'applications', ['status'], unique=False)
    op.create_table('ndvi_scans',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('parcel_id', sa.UUID(), nullable=False),
    sa.Column('ndvi', sa.Float(), nullable=False),
    sa.Column('flagged', sa.Boolean(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('scanned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parcel_id'], ['parcels.id'], name=op.f('fk_ndvi_scans_parcel_id_parcels'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ndvi_scans'))
    )
    op.create_index('ix_ndvi_scans_parcel', 'ndvi_scans', ['parcel_id', 'scanned_at'], unique=False)
    op.create_geospatial_table('signals',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tracking_code', sa.String(length=32), nullable=False),
    sa.Column('location', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('category', sa.Enum('DUMP', 'ABANDONED', 'SELF_SEIZURE', 'OTHER', name='signal_category', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'IN_REVIEW', 'CONFIRMED', 'REJECTED', name='signal_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('parcel_id', sa.UUID(), nullable=True),
    sa.Column('parcel_distance_m', sa.Float(), nullable=True),
    sa.Column('duplicate_of', sa.UUID(), nullable=True),
    sa.Column('reporter_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('reporter_lang', sa.Enum('ru', 'kk', name='lang', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('resolution_comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['duplicate_of'], ['signals.id'], name=op.f('fk_signals_duplicate_of_signals'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parcel_id'], ['parcels.id'], name=op.f('fk_signals_parcel_id_parcels'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signals')),
    sa.UniqueConstraint('tracking_code', name=op.f('uq_signals_tracking_code'))
    )
    op.create_geospatial_index('idx_signals_location', 'signals', ['location'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index('ix_signals_created_at', 'signals', ['created_at'], unique=False)
    op.create_index(op.f('ix_signals_duplicate_of'), 'signals', ['duplicate_of'], unique=False)
    op.create_index(op.f('ix_signals_parcel_id'), 'signals', ['parcel_id'], unique=False)
    op.create_index(op.f('ix_signals_reporter_chat_id'), 'signals', ['reporter_chat_id'], unique=False)
    op.create_index(op.f('ix_signals_status'), 'signals', ['status'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('target_type', sa.Enum('APPLICATION', 'SIGNAL', name='subscription_target', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['telegram_users.chat_id'], name=op.f('fk_subscriptions_chat_id_telegram_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions')),
    sa.UniqueConstraint('chat_id', 'target_type', 'target_id', name='uq_subscriptions_target')
    )
    op.create_index(op.f('ix_subscriptions_chat_id'), 'subscriptions', ['chat_id'], unique=False)
    op.create_index('ix_subscriptions_target', 'subscriptions', ['target_type', 'target_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_subscriptions_target', table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_chat_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_signals_status'), table_name='signals')
    op.drop_index(op.f('ix_signals_reporter_chat_id'), table_name='signals')
    op.drop_index(op.f('ix_signals_parcel_id'), table_name='signals')
    op.drop_index(op.f('ix_signals_duplicate_of'), table_name='signals')
    op.drop_index('ix_signals_created_at', table_name='signals')
    op.drop_geospatial_index('idx_signals_location', table_name='signals', postgresql_using='gist', column_name='location')
    op.drop_geospatial_table('signals')
    op.drop_index('ix_ndvi_scans_parcel', table_name='ndvi_scans')
    op.drop_table('ndvi_scans')
    op.drop_index(op.f('ix_applications_status'), table_name='applications')
    op.drop_table('applications')
    op.drop_table('tg_processed_updates')
    op.drop_table('telegram_users')
    op.drop_index('ix_status_transitions_entity', table_name='status_transitions')
    op.drop_table('status_transitions')
    op.drop_index('ix_photos_owner', table_name='photos')
    op.drop_geospatial_table('photos')
    op.drop_index(op.f('ix_parcels_status'), table_name='parcels')
    op.drop_index(op.f('ix_parcels_deadline_at'), table_name='parcels')
    op.drop_geospatial_index('idx_parcels_geometry', table_name='parcels', postgresql_using='gist', column_name='geometry')
    op.drop_geospatial_index('idx_parcels_centroid', table_name='parcels', postgresql_using='gist', column_name='centroid')
    op.drop_geospatial_table('parcels')
    op.drop_table('knowledge_questions')
    op.drop_table('geocode_cache')
    op.drop_table('events')
    # ### end Alembic commands ###
    op.execute("DROP SEQUENCE IF EXISTS signal_tracking_seq")
