"""land fund and mini app applications

Revision ID: af04450b275c
Revises: 75a0403f6078
Create Date: 2026-09-28 05:14:29.933142+00:00
"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op


revision: str = 'af04450b275c'
down_revision: str | None = '75a0403f6078'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_parcels',
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('parcel_id', sa.UUID(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('granted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_application_parcels_application_id_applications'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parcel_id'], ['parcels.id'], name=op.f('fk_application_parcels_parcel_id_parcels'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('application_id', 'parcel_id', name=op.f('pk_application_parcels'))
    )
    op.create_index(op.f('ix_application_parcels_parcel_id'), 'application_parcels', ['parcel_id'], unique=False)
    op.add_column('applications', sa.Column('source', sa.String(length=16), server_default='seed', nullable=False))
    op.add_column('applications', sa.Column('applicant_chat_id', sa.BigInteger(), nullable=True))
    op.add_column('applications', sa.Column('applicant_iin_masked', sa.String(length=16), nullable=True))
    op.add_column('applications', sa.Column('applicant_phone_masked', sa.String(length=24), nullable=True))
    op.add_column('applications', sa.Column('applicant_comment', sa.Text(), nullable=True))
    op.create_index(op.f('ix_applications_applicant_chat_id'), 'applications', ['applicant_chat_id'], unique=False)
    op.add_column('parcels', sa.Column('allocation_status', sa.Enum('NONE', 'OFFERED', 'RESERVED', 'ALLOCATED', name='allocation_status', native_enum=False, create_constraint=True, length=32), server_default='NONE', nullable=False))
    op.add_column('parcels', sa.Column('owner_chat_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_parcels_allocation_status'), 'parcels', ['allocation_status'], unique=False)
    op.create_index(op.f('ix_parcels_owner_chat_id'), 'parcels', ['owner_chat_id'], unique=False)
    # Mini App drafts (confirmed in Telegram) and cancellations; agricultural lease from the fund.
    op.drop_constraint(op.f("ck_applications_application_status"), "applications", type_="check")
    op.create_check_constraint(
        "application_status",
        "applications",
        "status IN ('DRAFT', 'UNDER_REVIEW', 'INSPECTION_SCHEDULED', 'APPROVED', 'REJECTED', 'CANCELLED')",
    )
    op.drop_constraint(op.f("ck_applications_application_type"), "applications", type_="check")
    op.create_check_constraint(
        "application_type",
        "applications",
        "type IN ('PURPOSE_CHANGE', 'LEASE_EXTENSION', 'IZHS_ALLOCATION', 'AGRO_LEASE')",
    )
    # Tracking numbers of new applications continue after the seeded ones (KZ-YYYY-5NN…).
    op.execute("CREATE SEQUENCE IF NOT EXISTS application_number_seq START 500")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP SEQUENCE IF EXISTS application_number_seq")
    op.execute("DELETE FROM applications WHERE status IN ('DRAFT', 'CANCELLED') OR type = 'AGRO_LEASE'")
    op.drop_constraint(op.f("ck_applications_application_status"), "applications", type_="check")
    op.create_check_constraint(
        "application_status",
        "applications",
        "status IN ('UNDER_REVIEW', 'INSPECTION_SCHEDULED', 'APPROVED', 'REJECTED')",
    )
    op.drop_constraint(op.f("ck_applications_application_type"), "applications", type_="check")
    op.create_check_constraint(
        "application_type", "applications", "type IN ('PURPOSE_CHANGE', 'LEASE_EXTENSION', 'IZHS_ALLOCATION')"
    )
    op.drop_index(op.f('ix_parcels_owner_chat_id'), table_name='parcels')
    op.drop_index(op.f('ix_parcels_allocation_status'), table_name='parcels')
    op.drop_column('parcels', 'owner_chat_id')
    op.drop_column('parcels', 'allocation_status')
    op.drop_index(op.f('ix_applications_applicant_chat_id'), table_name='applications')
    op.drop_column('applications', 'applicant_comment')
    op.drop_column('applications', 'applicant_phone_masked')
    op.drop_column('applications', 'applicant_iin_masked')
    op.drop_column('applications', 'applicant_chat_id')
    op.drop_column('applications', 'source')
    op.drop_index(op.f('ix_application_parcels_parcel_id'), table_name='application_parcels')
    op.drop_table('application_parcels')
    # ### end Alembic commands ###
