"""ndvi scan image chips

Revision ID: b64119cf998f
Revises: 9b1163620e1d
Create Date: 2026-09-25 17:15:37.807380+00:00
"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op


revision: str = 'b64119cf998f'
down_revision: str | None = '9b1163620e1d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ndvi_scans', sa.Column('chip_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ndvi_scans', 'chip_path')
    # ### end Alembic commands ###
