"""audit hash chain, photo hashes, acts registry

Revision ID: ed1f3e08fd36
Revises: b64119cf998f
Create Date: 2026-09-26 05:54:40.743518+00:00
"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'ed1f3e08fd36'
down_revision: str | None = 'b64119cf998f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('number', sa.String(length=32), nullable=False),
    sa.Column('parcel_id', sa.UUID(), nullable=False),
    sa.Column('cadastral_number', sa.String(length=32), nullable=False),
    sa.Column('parcel_status', sa.String(length=32), nullable=False),
    sa.Column('lang', sa.Enum('ru', 'kk', name='lang', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('pdf_sha256', sa.String(length=64), nullable=False),
    sa.Column('chain_head', sa.String(length=64), nullable=False),
    sa.Column('chain_length', sa.Integer(), nullable=False),
    sa.Column('photo_hashes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('issued_by', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parcel_id'], ['parcels.id'], name=op.f('fk_acts_parcel_id_parcels'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_acts')),
    sa.UniqueConstraint('number', name=op.f('uq_acts_number'))
    )
    op.add_column('photos', sa.Column('sha256', sa.String(length=64), nullable=True))
    op.add_column('photos', sa.Column('phash', sa.String(length=16), nullable=True))
    op.create_index(op.f('ix_photos_phash'), 'photos', ['phash'], unique=False)
    op.add_column('status_transitions', sa.Column('prev_hash', sa.String(length=64), nullable=True))
    op.add_column('status_transitions', sa.Column('hash', sa.String(length=64), nullable=True))
    op.create_unique_constraint(op.f('uq_status_transitions_hash'), 'status_transitions', ['hash'])
    op.execute("CREATE SEQUENCE IF NOT EXISTS act_number_seq START 1")
    _backfill_chain()
    # ### end Alembic commands ###


def _backfill_chain() -> None:
    """Link existing audit rows into the hash chain (in id order)."""
    from app.domain.audit_chain import GENESIS_HASH, transition_hash

    bind = op.get_bind()
    rows = bind.execute(
        sa.text(
            "SELECT id, entity_type, entity_id, from_status, to_status, actor, comment, meta, created_at "
            "FROM status_transitions ORDER BY id"
        )
    ).fetchall()
    prev = GENESIS_HASH
    for row in rows:
        digest = transition_hash(
            prev,
            entity_type=row.entity_type,
            entity_id=str(row.entity_id),
            from_status=row.from_status,
            to_status=row.to_status,
            actor=row.actor,
            comment=row.comment,
            meta=row.meta,
            created_at=row.created_at,
        )
        bind.execute(
            sa.text("UPDATE status_transitions SET prev_hash = :p, hash = :h WHERE id = :id"),
            {"p": prev, "h": digest, "id": row.id},
        )
        prev = digest


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_status_transitions_hash'), 'status_transitions', type_='unique')
    op.drop_column('status_transitions', 'hash')
    op.drop_column('status_transitions', 'prev_hash')
    op.drop_index(op.f('ix_photos_phash'), table_name='photos')
    op.drop_column('photos', 'phash')
    op.drop_column('photos', 'sha256')
    op.drop_table('acts')
    op.execute("DROP SEQUENCE IF EXISTS act_number_seq")
    # ### end Alembic commands ###
