"""sentinel scene metadata

Revision ID: 9b1163620e1d
Revises: 43af945b0cc6
Create Date: 2026-09-25 07:15:47.315350+00:00
"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op


revision: str = '9b1163620e1d'
down_revision: str | None = '43af945b0cc6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ndvi_scans', sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('ndvi_scans', sa.Column('scene_id', sa.String(length=64), nullable=True))
    op.add_column('ndvi_scans', sa.Column('valid_fraction', sa.Float(), nullable=True))
    op.add_column('parcels', sa.Column('ndvi_observed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('parcels', sa.Column('ndvi_scene_id', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parcels', 'ndvi_scene_id')
    op.drop_column('parcels', 'ndvi_observed_at')
    op.drop_column('ndvi_scans', 'valid_fraction')
    op.drop_column('ndvi_scans', 'scene_id')
    op.drop_column('ndvi_scans', 'observed_at')
    # ### end Alembic commands ###
