/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Which login flow the web panel must use */
        get: operations["auth_config_api_v1_auth_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Local dev login (AUTH_MODE=local only) */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/parcels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Parcels as GeoJSON FeatureCollection */
        get: operations["list_parcels_api_v1_parcels_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/parcels/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search by cadastral number or address */
        get: operations["search_parcels_api_v1_parcels_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/parcels/{parcel_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Parcel */
        get: operations["get_parcel_api_v1_parcels__parcel_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update deadline / assigned inspector */
        patch: operations["update_parcel_api_v1_parcels__parcel_id__patch"];
        trace?: never;
    };
    "/api/v1/parcels/{parcel_id}/transitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change parcel status (state machine) */
        post: operations["transition_parcel_api_v1_parcels__parcel_id__transitions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/parcels/{parcel_id}/photos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload inspector photos (multipart, up to 10 files) */
        post: operations["upload_parcel_photos_api_v1_parcels__parcel_id__photos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/parcels/{parcel_id}/cadastre": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reconcile with the state cadastre registry (ГБД ЗКС adapter, demo) */
        get: operations["cadastre_record_api_v1_parcels__parcel_id__cadastre_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/parcels/{parcel_id}/act.pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Inspection act (PDF) in the interface language */
        get: operations["inspection_act_api_v1_parcels__parcel_id__act_pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/signals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Signals queue (open first, newest on top) */
        get: operations["list_signals_api_v1_signals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/signals/{signal_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Signal */
        get: operations["get_signal_api_v1_signals__signal_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/signals/{signal_id}/transitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Take into work / confirm (parcel → VIOLATION) / reject; the citizen is notified */
        post: operations["transition_signal_api_v1_signals__signal_id__transitions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Applications */
        get: operations["list_applications_api_v1_applications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{application_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Application */
        get: operations["get_application_api_v1_applications__application_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{application_id}/transitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change application status with RU/KZ explanation; subscribers get a Telegram push */
        post: operations["transition_application_api_v1_applications__application_id__transitions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard */
        get: operations["dashboard_api_v1_stats_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/satellite/ndvi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** NDVI layer (demo provider) */
        get: operations["ndvi_layer_api_v1_satellite_ndvi_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/satellite/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run a scan now */
        post: operations["satellite_scan_api_v1_satellite_scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Event feed (realtime fallback) */
        get: operations["list_events_api_v1_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/export/parcels.geojson": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Geojson */
        get: operations["export_geojson_api_v1_export_parcels_geojson_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/export/parcels.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Csv */
        get: operations["export_csv_api_v1_export_parcels_csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dev/simulate-signal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a signal exactly as the bot would (for e2e tests and demo fallback) */
        post: operations["simulate_signal_api_v1_dev_simulate_signal_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dev/demo-reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Wipe domain data and re-seed the demo */
        post: operations["demo_reset_api_v1_dev_demo_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApplicationList */
        ApplicationList: {
            /** Items */
            items: components["schemas"]["ApplicationOut"][];
            /** Total */
            total: number;
        };
        /** ApplicationOut */
        ApplicationOut: {
            /** Id */
            id: string;
            /** Tracking Number */
            tracking_number: string;
            /** Applicant Name */
            applicant_name: string;
            type: components["schemas"]["ApplicationType"];
            status: components["schemas"]["ApplicationStatus"];
            /** Status Comment Ru */
            status_comment_ru: string | null;
            /** Status Comment Kk */
            status_comment_kk: string | null;
            /** Inspection Date */
            inspection_date: string | null;
            /** Parcel Id */
            parcel_id: string | null;
            /** Parcel Cadastral Number */
            parcel_cadastral_number: string | null;
            /**
             * Submitted At
             * Format: date-time
             */
            submitted_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Subscribers Count */
            subscribers_count: number;
            /** Allowed Transitions */
            allowed_transitions: components["schemas"]["ApplicationStatus"][];
            /** History */
            history: components["schemas"]["TransitionOut"][];
        };
        /**
         * ApplicationStatus
         * @enum {string}
         */
        ApplicationStatus: "UNDER_REVIEW" | "INSPECTION_SCHEDULED" | "APPROVED" | "REJECTED";
        /** ApplicationTransitionRequest */
        ApplicationTransitionRequest: {
            to: components["schemas"]["ApplicationStatus"];
            /** Comment Ru */
            comment_ru: string;
            /** Comment Kk */
            comment_kk: string;
            /** Inspection Date */
            inspection_date?: string | null;
        };
        /**
         * ApplicationType
         * @enum {string}
         */
        ApplicationType: "PURPOSE_CHANGE" | "LEASE_EXTENSION" | "IZHS_ALLOCATION";
        /** AuthConfig */
        AuthConfig: {
            /**
             * Mode
             * @enum {string}
             */
            mode: "supabase" | "local";
        };
        /** Body_upload_parcel_photos_api_v1_parcels__parcel_id__photos_post */
        Body_upload_parcel_photos_api_v1_parcels__parcel_id__photos_post: {
            /**
             * Files
             * @description JPEG/PNG/WebP images
             */
            files: string[];
        };
        /**
         * CadastreRecord
         * @description Record as returned by an external cadastre registry (ГБД ЗКС) adapter.
         */
        CadastreRecord: {
            /** Provider */
            provider: string;
            /** Cadastral Number */
            cadastral_number: string;
            /** Purpose */
            purpose: string;
            /** Area Ha */
            area_ha: number;
            /** Right Type */
            right_type: string;
            /** Right Holder */
            right_holder: string;
            /** Registered At */
            registered_at: string | null;
            /** Encumbrances */
            encumbrances: string[];
            /** Matches Local */
            matches_local: boolean;
            /** Discrepancies */
            discrepancies: string[];
        };
        /** DashboardStats */
        DashboardStats: {
            kpi: components["schemas"]["Kpi"];
            /** Signals By Day */
            signals_by_day: components["schemas"]["DayCount"][];
            /** Violations By Type */
            violations_by_type: components["schemas"]["ViolationTypeCount"][];
            /** Status Counts */
            status_counts: components["schemas"]["StatusCount"][];
            /** Upcoming Deadlines */
            upcoming_deadlines: components["schemas"]["UpcomingDeadline"][];
        };
        /** DayCount */
        DayCount: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Count */
            count: number;
        };
        /** DemoResetResponse */
        DemoResetResponse: {
            /** Parcels */
            parcels: number;
            /** Applications */
            applications: number;
            /** Signals */
            signals: number;
        };
        /** ErrorInfo */
        ErrorInfo: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /**
             * Details
             * @default {}
             */
            details?: {
                [key: string]: unknown;
            };
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorInfo"];
        };
        /** EventList */
        EventList: {
            /** Items */
            items: components["schemas"]["EventOut"][];
            /** Last Id */
            last_id: number;
        };
        /** EventOut */
        EventOut: {
            /** Id */
            id: number;
            /** Type */
            type: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** HealthOut */
        HealthOut: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Version */
            version: string;
            /** Env */
            env: string;
            /** Database */
            database: boolean;
            /** Redis */
            redis: boolean;
            /**
             * Bot
             * @enum {string}
             */
            bot: "polling" | "webhook" | "disabled";
            /** Storage */
            storage: string;
        };
        /** InspectorOut */
        InspectorOut: {
            /** Id */
            id: string;
            /** Email */
            email: string | null;
            /** Name */
            name: string;
        };
        /** Kpi */
        Kpi: {
            /** Parcels Total */
            parcels_total: number;
            /** Area Total Ha */
            area_total_ha: number;
            /** Violations Active */
            violations_active: number;
            /** In Remediation */
            in_remediation: number;
            /** Overdue */
            overdue: number;
            /** Signals 7D */
            signals_7d: number;
            /** Signals New */
            signals_new: number;
            /** Avg Reaction Hours */
            avg_reaction_hours: number | null;
        };
        /**
         * Lang
         * @enum {string}
         */
        Lang: "ru" | "kk";
        /** LngLat */
        LngLat: {
            /** Lon */
            lon: number;
            /** Lat */
            lat: number;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** NdviLayer */
        NdviLayer: {
            /** Provider */
            provider: string;
            /** Is Demo */
            is_demo: boolean;
            /** Scanned At */
            scanned_at: string | null;
            /** Threshold */
            threshold: number;
            /** Readings */
            readings: components["schemas"]["NdviReadingOut"][];
        };
        /** NdviReadingOut */
        NdviReadingOut: {
            /** Parcel Id */
            parcel_id: string;
            /** Ndvi */
            ndvi: number;
            /** Flagged */
            flagged: boolean;
            /**
             * Scanned At
             * Format: date-time
             */
            scanned_at: string;
        };
        /**
         * OwnerType
         * @enum {string}
         */
        OwnerType: "PRIVATE" | "LEASE" | "STATE";
        /** ParcelDetail */
        ParcelDetail: {
            /** Id */
            id: string;
            /** Cadastral Number */
            cadastral_number: string;
            status: components["schemas"]["ParcelStatus"];
            violation_type: components["schemas"]["ViolationType"] | null;
            purpose: components["schemas"]["ParcelPurpose"];
            owner_type: components["schemas"]["OwnerType"];
            /** Area Ha */
            area_ha: number;
            /** Address Ru */
            address_ru: string;
            /** Address Kk */
            address_kk: string;
            /** District */
            district: string;
            /** Deadline At */
            deadline_at: string | null;
            /** Is Overdue */
            is_overdue: boolean;
            /** Ndvi */
            ndvi: number | null;
            /** Ndvi Flagged */
            ndvi_flagged: boolean;
            /** Open Signals Count */
            open_signals_count: number;
            /** Geometry */
            geometry: {
                [key: string]: unknown;
            };
            centroid: components["schemas"]["LngLat"];
            /**
             * Bbox
             * @description minLon, minLat, maxLon, maxLat
             */
            bbox: number[];
            /** Lease Until */
            lease_until: string | null;
            /** Inspector Id */
            inspector_id: string | null;
            /** Ndvi Scanned At */
            ndvi_scanned_at: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Allowed Transitions */
            allowed_transitions: components["schemas"]["ParcelStatus"][];
            /** Photos */
            photos: components["schemas"]["PhotoOut"][];
            /** Signals */
            signals: components["schemas"]["SignalSummary"][];
            /** History */
            history: components["schemas"]["TransitionOut"][];
        };
        /** ParcelFeature */
        ParcelFeature: {
            /**
             * Type
             * @default Feature
             * @constant
             */
            type?: "Feature";
            /** Id */
            id: string;
            /** Geometry */
            geometry: {
                [key: string]: unknown;
            };
            properties: components["schemas"]["ParcelProperties"];
        };
        /** ParcelFeatureCollection */
        ParcelFeatureCollection: {
            /**
             * Type
             * @default FeatureCollection
             * @constant
             */
            type?: "FeatureCollection";
            /** Features */
            features: components["schemas"]["ParcelFeature"][];
        };
        /** ParcelProperties */
        ParcelProperties: {
            /** Id */
            id: string;
            /** Cadastral Number */
            cadastral_number: string;
            status: components["schemas"]["ParcelStatus"];
            violation_type: components["schemas"]["ViolationType"] | null;
            purpose: components["schemas"]["ParcelPurpose"];
            owner_type: components["schemas"]["OwnerType"];
            /** Area Ha */
            area_ha: number;
            /** Address Ru */
            address_ru: string;
            /** Address Kk */
            address_kk: string;
            /** District */
            district: string;
            /** Deadline At */
            deadline_at: string | null;
            /** Is Overdue */
            is_overdue: boolean;
            /** Ndvi */
            ndvi: number | null;
            /** Ndvi Flagged */
            ndvi_flagged: boolean;
            /** Open Signals Count */
            open_signals_count: number;
        };
        /**
         * ParcelPurpose
         * @enum {string}
         */
        ParcelPurpose: "IZHS" | "AGRICULTURE" | "COMMERCIAL" | "INDUSTRIAL" | "LPH";
        /** ParcelSearchResult */
        ParcelSearchResult: {
            /** Id */
            id: string;
            /** Cadastral Number */
            cadastral_number: string;
            /** Address Ru */
            address_ru: string;
            /** Address Kk */
            address_kk: string;
            status: components["schemas"]["ParcelStatus"];
            centroid: components["schemas"]["LngLat"];
            /**
             * Bbox
             * @description minLon, minLat, maxLon, maxLat
             */
            bbox: number[];
        };
        /**
         * ParcelStatus
         * @enum {string}
         */
        ParcelStatus: "OK" | "UNDER_CHECK" | "VIOLATION" | "IN_REMEDIATION" | "RESOLVED" | "RETURNED_TO_STATE";
        /** ParcelTransitionRequest */
        ParcelTransitionRequest: {
            to: components["schemas"]["ParcelStatus"];
            /** Comment */
            comment: string;
            violation_type?: components["schemas"]["ViolationType"] | null;
            /** Deadline At */
            deadline_at?: string | null;
        };
        /** ParcelUpdateRequest */
        ParcelUpdateRequest: {
            /** Deadline At */
            deadline_at?: string | null;
            /** Inspector Id */
            inspector_id?: string | null;
            /**
             * Clear Deadline
             * @default false
             */
            clear_deadline?: boolean;
        };
        /** PhotoOut */
        PhotoOut: {
            /** Id */
            id: string;
            /** Url */
            url: string;
            /** Thumb Url */
            thumb_url: string;
            /** Source */
            source: string;
            /** Taken At */
            taken_at: string | null;
            /** Lat */
            lat: number | null;
            /** Lon */
            lon: number | null;
            /** Uploaded By */
            uploaded_by: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** SatelliteScanResult */
        SatelliteScanResult: {
            /** Scanned */
            scanned: number;
            /** Flagged */
            flagged: number;
            /** Provider */
            provider: string;
        };
        /**
         * SignalCategory
         * @enum {string}
         */
        SignalCategory: "DUMP" | "ABANDONED" | "SELF_SEIZURE" | "OTHER";
        /** SignalDetail */
        SignalDetail: {
            /** Id */
            id: string;
            /** Tracking Code */
            tracking_code: string;
            category: components["schemas"]["SignalCategory"];
            status: components["schemas"]["SignalStatus"];
            /** Description */
            description: string | null;
            /** Address */
            address: string | null;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Parcel Id */
            parcel_id: string | null;
            /** Parcel Cadastral Number */
            parcel_cadastral_number: string | null;
            /** Duplicate Of */
            duplicate_of: string | null;
            /**
             * Reports Count
             * @description Root signal + its duplicates (how many citizens reported)
             */
            reports_count: number;
            /** Thumb Url */
            thumb_url: string | null;
            /** Photos Count */
            photos_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            reporter_lang: components["schemas"]["Lang"];
            /** Has Reporter */
            has_reporter: boolean;
            /** Parcel Distance M */
            parcel_distance_m: number | null;
            /** Resolution Comment */
            resolution_comment: string | null;
            /** Allowed Transitions */
            allowed_transitions: components["schemas"]["SignalStatus"][];
            /** Photos */
            photos: components["schemas"]["PhotoOut"][];
            /** Duplicates */
            duplicates: components["schemas"]["SignalSummary"][];
            /** History */
            history: components["schemas"]["TransitionOut"][];
        };
        /** SignalList */
        SignalList: {
            /** Items */
            items: components["schemas"]["SignalSummary"][];
            /** Total */
            total: number;
        };
        /**
         * SignalStatus
         * @enum {string}
         */
        SignalStatus: "NEW" | "IN_REVIEW" | "CONFIRMED" | "REJECTED";
        /** SignalSummary */
        SignalSummary: {
            /** Id */
            id: string;
            /** Tracking Code */
            tracking_code: string;
            category: components["schemas"]["SignalCategory"];
            status: components["schemas"]["SignalStatus"];
            /** Description */
            description: string | null;
            /** Address */
            address: string | null;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Parcel Id */
            parcel_id: string | null;
            /** Parcel Cadastral Number */
            parcel_cadastral_number: string | null;
            /** Duplicate Of */
            duplicate_of: string | null;
            /**
             * Reports Count
             * @description Root signal + its duplicates (how many citizens reported)
             */
            reports_count: number;
            /** Thumb Url */
            thumb_url: string | null;
            /** Photos Count */
            photos_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** SignalTransitionRequest */
        SignalTransitionRequest: {
            to: components["schemas"]["SignalStatus"];
            /** Comment */
            comment: string;
            violation_type?: components["schemas"]["ViolationType"] | null;
            /** Deadline At */
            deadline_at?: string | null;
        };
        /** SimulateSignalRequest */
        SimulateSignalRequest: {
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** @default DUMP */
            category?: components["schemas"]["SignalCategory"];
            /** Description */
            description?: string | null;
            /** Chat Id */
            chat_id?: number | null;
            /** @default ru */
            lang?: components["schemas"]["Lang"];
            /**
             * Photos
             * @description Number of generated placeholder photos
             * @default 1
             */
            photos?: number;
        };
        /** SimulateSignalResponse */
        SimulateSignalResponse: {
            signal: components["schemas"]["SignalSummary"];
            /** Parcel Status */
            parcel_status: string | null;
        };
        /** StatusCount */
        StatusCount: {
            status: components["schemas"]["ParcelStatus"];
            /** Count */
            count: number;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             * @constant
             */
            token_type?: "bearer";
            /** Expires In */
            expires_in: number;
            user: components["schemas"]["InspectorOut"];
        };
        /** TransitionOut */
        TransitionOut: {
            /** Id */
            id: number;
            /** From Status */
            from_status: string | null;
            /** To Status */
            to_status: string;
            /** Actor */
            actor: string;
            /** Comment */
            comment: string | null;
            /** Meta */
            meta: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** UpcomingDeadline */
        UpcomingDeadline: {
            /** Parcel Id */
            parcel_id: string;
            /** Cadastral Number */
            cadastral_number: string;
            status: components["schemas"]["ParcelStatus"];
            violation_type: components["schemas"]["ViolationType"] | null;
            /**
             * Deadline At
             * Format: date-time
             */
            deadline_at: string;
            /** Days Left */
            days_left: number;
        };
        /**
         * ViolationType
         * @enum {string}
         */
        ViolationType: "UNUSED" | "SELF_SEIZURE" | "DUMP" | "MISUSE";
        /** ViolationTypeCount */
        ViolationTypeCount: {
            violation_type: components["schemas"]["ViolationType"];
            /** Count */
            count: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
            /** @description Database unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    auth_config_api_v1_auth_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthConfig"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InspectorOut"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_parcels_api_v1_parcels_get: {
        parameters: {
            query?: {
                /** @description minLon,minLat,maxLon,maxLat */
                bbox?: string | null;
                status?: components["schemas"]["ParcelStatus"][];
                violation_type?: components["schemas"]["ViolationType"][];
                purpose?: components["schemas"]["ParcelPurpose"][];
                overdue?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParcelFeatureCollection"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    search_parcels_api_v1_parcels_search_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParcelSearchResult"][];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_parcel_api_v1_parcels__parcel_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                parcel_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParcelDetail"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    update_parcel_api_v1_parcels__parcel_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                parcel_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParcelUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParcelDetail"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    transition_parcel_api_v1_parcels__parcel_id__transitions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                parcel_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParcelTransitionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParcelDetail"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Transition not allowed */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    upload_parcel_photos_api_v1_parcels__parcel_id__photos_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                parcel_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_parcel_photos_api_v1_parcels__parcel_id__photos_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParcelDetail"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    cadastre_record_api_v1_parcels__parcel_id__cadastre_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                parcel_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CadastreRecord"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    inspection_act_api_v1_parcels__parcel_id__act_pdf_get: {
        parameters: {
            query?: {
                lang?: components["schemas"]["Lang"];
            };
            header?: never;
            path: {
                parcel_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": unknown;
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_signals_api_v1_signals_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["SignalStatus"][];
                include_duplicates?: boolean;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignalList"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_signal_api_v1_signals__signal_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                signal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignalDetail"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    transition_signal_api_v1_signals__signal_id__transitions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                signal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignalTransitionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignalDetail"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Transition not allowed */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_applications_api_v1_applications_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["ApplicationStatus"][];
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationList"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_application_api_v1_applications__application_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationOut"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    transition_application_api_v1_applications__application_id__transitions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationTransitionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationOut"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Transition not allowed */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    dashboard_api_v1_stats_dashboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardStats"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    ndvi_layer_api_v1_satellite_ndvi_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NdviLayer"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    satellite_scan_api_v1_satellite_scan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SatelliteScanResult"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_events_api_v1_events_get: {
        parameters: {
            query?: {
                /** @description Return events with id > since */
                since?: number | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventList"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    export_geojson_api_v1_export_parcels_geojson_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/geo+json": unknown;
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    export_csv_api_v1_export_parcels_csv_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": unknown;
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    simulate_signal_api_v1_dev_simulate_signal_post: {
        parameters: {
            query?: never;
            header?: {
                "x-service-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulateSignalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulateSignalResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    demo_reset_api_v1_dev_demo_reset_post: {
        parameters: {
            query?: never;
            header?: {
                "x-service-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemoResetResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
